# Autogenerated wrapper script for librel_ant_parser_jll for aarch64-linux-gnu-cxx11
export librel_ant_parser_0_1, librel_ant_parser_0_2, rel_proto

using Libuuid_jll
using Antlr4CppRuntime_jll
using protoc_jll
JLLWrappers.@generate_wrapper_header("librel_ant_parser")
JLLWrappers.@declare_library_product(librel_ant_parser_0_1, "librel-ant-parser-0-1.so")
JLLWrappers.@declare_library_product(librel_ant_parser_0_2, "librel-ant-parser-0-2.so")
JLLWrappers.@declare_file_product(rel_proto)
function __init__()
    JLLWrappers.@generate_init_header(Libuuid_jll, Antlr4CppRuntime_jll, protoc_jll)
    JLLWrappers.@init_library_product(
        librel_ant_parser_0_1,
        "lib/librel-ant-parser-0-1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librel_ant_parser_0_2,
        "lib/librel-ant-parser-0-2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        rel_proto,
        "Rel.proto",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
