# Autogenerated wrapper script for librel_ant_parser_jll for aarch64-apple-darwin
export librel_ant_parser_0_1, librel_ant_parser_0_2, rel_proto

using Antlr4CppRuntime_jll
using protoc_jll
JLLWrappers.@generate_wrapper_header("librel_ant_parser")
JLLWrappers.@declare_library_product(librel_ant_parser_0_1, "@rpath/librel-ant-parser-0-1.dylib")
JLLWrappers.@declare_library_product(librel_ant_parser_0_2, "@rpath/librel-ant-parser-0-2.dylib")
JLLWrappers.@declare_file_product(rel_proto)
function __init__()
    JLLWrappers.@generate_init_header(Antlr4CppRuntime_jll, protoc_jll)
    JLLWrappers.@init_library_product(
        librel_ant_parser_0_1,
        "lib/librel-ant-parser-0-1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librel_ant_parser_0_2,
        "lib/librel-ant-parser-0-2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        rel_proto,
        "Rel.proto",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
